import { compact } from './text.js';

// よくあるサブスクの辞書。
// re はカード明細の利用先（記号・空白を除いて大文字にしたもの）と、雑入力の文章の両方に当てる。
// 上から順に調べるので、具体的なもの（YouTube Music・DMM英会話）を、あいまいなもの（YouTube・DMM）より先に置く。
// 親会社の名前だけで当たるもの（MICROSOFT・DMM・NHK など）は、いちばん下の「親会社」に置く。
//   usd     : ドル建てで請求されることが多い（ヒントの表示だけに使う）
//   generic : App Store のように、中身が複数のサービスになりうる請求元
//   textOnly: 雑入力でだけ使う、あいまいな呼び方
//   channel : 支払い経路（App Store 経由など）
// 金額は辞書に持たない（値上げで変わるので、推測で入れると数字が信用できなくなる）

// 短い英字の名前は、前後が英数字でないときだけ当てる（REPAIRS の中の PAIRS などに当てない）
const w = (t) => `(?<![A-Z0-9])(?:${t})(?![A-Z0-9])`;
// 前だけ見る（DMM.COM のように後ろに英字が続く書き方も当てたいとき）
const b = (t) => `(?<![A-Z0-9])(?:${t})`;

const LIST = [
  // ---------- 動画 ----------
  { id: 'netflix', name: 'Netflix', cat: 'video', re: 'NETFLIX|ネットフリックス|ネトフリ' },
  { id: 'unext', name: 'U-NEXT', cat: 'video', re: 'U\\s*-?\\s*NEXT|ユーネクスト' },
  { id: 'hulu', name: 'Hulu', cat: 'video', re: 'HULU|フールー' },
  { id: 'disneyplus', name: 'Disney+', cat: 'video', re: 'DISNEY|ディズニー\\s*(\\+|プラス)' },
  { id: 'dazn', name: 'DAZN', cat: 'video', re: 'DAZN|ダゾーン' },
  { id: 'abema', name: 'ABEMA', cat: 'video', re: 'ABEMA|アベマ' },
  { id: 'danime', name: 'dアニメストア', cat: 'video', re: 'D\\s*アニメ|DANIME' },
  { id: 'lemino', name: 'Lemino', cat: 'video', re: 'LEMINO|レミノ' },
  { id: 'ytmusic', name: 'YouTube Music', cat: 'music', re: 'YOUTUBE\\s*MUSIC|ユーチューブ\\s*ミュージック' },
  { id: 'ytpremium', name: 'YouTube Premium', cat: 'video', re: 'YOUTUBE|ユーチューブ|ようつべ' },
  { id: 'niconico', name: 'niconicoプレミアム', cat: 'video', re: 'NICONICO|ニコニコ|ニコ動|ドワンゴ|DWANGO' },
  { id: 'dmmtv', name: 'DMMプレミアム（DMM TV）', cat: 'video', re: 'DMM\\s*TV|DMM\\s*プレミアム|DMMPREMIUM' },
  { id: 'telasa', name: 'TELASA', cat: 'video', re: 'TELASA|テラサ' },
  { id: 'fod', name: 'FODプレミアム', cat: 'video', re: `${w('FOD')}|${b('FOD\\s*PREMIUM')}|フジテレビ\\s*オン\\s*デマンド` },
  { id: 'wowow', name: 'WOWOW', cat: 'video', re: 'WOWOW|ワウワウ' },
  { id: 'skyperfect', name: 'スカパー！', cat: 'video', re: 'スカパー|SKY\\s*PERFECT|SKYPERFECTV' },
  { id: 'jsports', name: 'J SPORTS', cat: 'video', re: 'J\\s*SPORTS|ジェイスポーツ' },
  { id: 'spotv', name: 'SPOTV NOW', cat: 'video', re: 'SPOTV' },
  { id: 'rakutentv', name: 'Rakuten TV', cat: 'video', re: 'RAKUTEN\\s*TV|楽天\\s*TV' },
  { id: 'nhkod', name: 'NHKオンデマンド', cat: 'video', re: 'NHK\\s*オンデマンド|NHK\\s*ON\\s*DEMAND' },
  { id: 'appletv', name: 'Apple TV+', cat: 'video', re: 'APPLE\\s*TV|アップル\\s*TV', channel: 'appstore' },
  { id: 'crunchyroll', name: 'Crunchyroll', cat: 'video', re: 'CRUNCHYROLL|クランチロール', usd: true },
  { id: 'bandaich', name: 'バンダイチャンネル', cat: 'video', re: 'バンダイ\\s*チャンネル|BANDAI\\s*CHANNEL' },
  { id: 'animehoudai', name: 'アニメ放題', cat: 'video', re: 'アニメ放題' },
  { id: 'hikaritv', name: 'ひかりTV', cat: 'video', re: 'ひかり\\s*TV|HIKARI\\s*TV' },
  { id: 'jcom', name: 'J:COM', cat: 'video', re: `${w('J\\s*:?\\s*COM')}|ジェイコム` },
  { id: 'discas', name: 'TSUTAYA DISCAS', cat: 'video', re: 'DISCAS|ディスカス' },
  { id: 'twitch', name: 'Twitch', cat: 'video', re: 'TWITCH|ツイッチ', usd: true },
  { id: 'paravi', name: 'Paravi', cat: 'video', re: 'PARAVI|パラビ' },
  { id: 'rakutenpw', name: 'Rakuten パ・リーグ Special', cat: 'video', re: 'パ\\s*・?\\s*リーグ\\s*SPECIAL|パリーグスペシャル' },
  { id: 'dazn-baseball', name: 'DAZN BASEBALL', cat: 'video', re: 'DAZN\\s*BASEBALL' },

  // ---------- 音楽・音声 ----------
  { id: 'spotify', name: 'Spotify', cat: 'music', re: 'SPOTIFY|スポティファイ|スポティ' },
  { id: 'applemusic', name: 'Apple Music', cat: 'music', re: 'APPLE\\s*MUSIC|アップル\\s*ミュージック', channel: 'appstore' },
  { id: 'amazonmusic', name: 'Amazon Music Unlimited', cat: 'music', re: 'AMAZON\\s*MUSIC|アマゾン\\s*ミュージック|AMZN\\s*MUSIC' },
  { id: 'linemusic', name: 'LINE MUSIC', cat: 'music', re: 'LINE\\s*MUSIC|ライン\\s*ミュージック' },
  { id: 'awa', name: 'AWA', cat: 'music', re: `${w('AWA')}|AWA\\s*(MUSIC|株式会社)` },
  { id: 'rakutenmusic', name: '楽天ミュージック', cat: 'music', re: '楽天\\s*ミュージック|RAKUTEN\\s*MUSIC' },
  { id: 'mora', name: 'mora qualitas', cat: 'music', re: 'MORA\\s*QUALITAS|モーラ' },
  { id: 'dhits', name: 'dヒッツ', cat: 'music', re: 'D\\s*ヒッツ|DHITS' },
  { id: 'recochoku', name: 'レコチョク', cat: 'music', re: 'レコチョク|RECOCHOKU' },
  { id: 'deezer', name: 'Deezer', cat: 'music', re: 'DEEZER' },
  { id: 'tidal', name: 'TIDAL', cat: 'music', re: w('TIDAL') },
  { id: 'soundcloud', name: 'SoundCloud', cat: 'music', re: 'SOUNDCLOUD|サウンドクラウド' },
  { id: 'kkbox', name: 'KKBOX', cat: 'music', re: 'KKBOX' },
  { id: 'utapass', name: 'うたパス', cat: 'music', re: 'うたパス|UTAPASS' },
  { id: 'musicjp', name: 'music.jp', cat: 'music', re: 'MUSIC\\s*\\.?\\s*JP|ミュージック\\s*ドット\\s*JP' },
  { id: 'joysound', name: 'JOYSOUND', cat: 'music', re: 'JOYSOUND|ジョイサウンド' },
  { id: 'audible', name: 'Audible', cat: 'music', re: 'AUDIBLE|オーディブル' },
  { id: 'audiobookjp', name: 'audiobook.jp', cat: 'music', re: 'AUDIOBOOK|オーディオブック' },
  { id: 'voicy', name: 'Voicy', cat: 'music', re: 'VOICY|ボイシー' },

  // ---------- AI ----------
  { id: 'chatgpt', name: 'ChatGPT', cat: 'ai', re: 'CHAT\\s*GPT|OPENAI|チャット\\s*GPT', usd: true },
  { id: 'claude', name: 'Claude', cat: 'ai', re: 'CLAUDE|ANTHROPIC|クロード', usd: true },
  { id: 'gemini', name: 'Gemini（Google AI Pro）', cat: 'ai', re: 'GEMINI|ジェミニ|GOOGLE\\s*ONE\\s*AI|GOOGLE\\s*AI\\s*(PRO|ULTRA|PREMIUM)' },
  { id: 'perplexity', name: 'Perplexity', cat: 'ai', re: 'PERPLEXITY|パープレキシティ|パープレ', usd: true },
  { id: 'grok', name: 'Grok', cat: 'ai', re: `SUPER\\s*GROK|GROK|${w('XAI')}|グロック`, usd: true },
  { id: 'midjourney', name: 'Midjourney', cat: 'ai', re: 'MIDJOURNEY|ミッドジャーニー', usd: true },
  { id: 'ghcopilot', name: 'GitHub Copilot', cat: 'ai', re: 'GITHUB\\s*COPILOT', usd: true },
  { id: 'mscopilot', name: 'Microsoft Copilot Pro', cat: 'ai', re: 'COPILOT\\s*PRO|MICROSOFT\\s*COPILOT' },
  { id: 'copilot', name: 'Copilot', cat: 'ai', re: 'COPILOT|コパイロット', usd: true },
  { id: 'cursor', name: 'Cursor', cat: 'ai', re: `${b('CURSOR')}|ANYSPHERE`, usd: true },
  { id: 'windsurf', name: 'Windsurf', cat: 'ai', re: 'WINDSURF|CODEIUM', usd: true },
  { id: 'replit', name: 'Replit', cat: 'ai', re: 'REPLIT', usd: true },
  { id: 'lovable', name: 'Lovable', cat: 'ai', re: 'LOVABLE', usd: true },
  { id: 'bolt', name: 'Bolt', cat: 'ai', re: 'BOLT\\s*\\.?\\s*NEW|STACKBLITZ', usd: true },
  { id: 'v0', name: 'v0（Vercel）', cat: 'ai', re: `${w('V0')}`, usd: true },
  { id: 'poe', name: 'Poe', cat: 'ai', re: `${w('POE')}|QUORA`, usd: true },
  { id: 'felo', name: 'Felo', cat: 'ai', re: `${w('FELO')}|${b('FELO\\s*AI')}` },
  { id: 'genspark', name: 'Genspark', cat: 'ai', re: 'GENSPARK', usd: true },
  { id: 'manus', name: 'Manus', cat: 'ai', re: `${w('MANUS')}|${b('MANUS\\s*AI')}`, usd: true },
  { id: 'notebooklm', name: 'NotebookLM', cat: 'ai', re: 'NOTEBOOK\\s*LM' },
  { id: 'deepl', name: 'DeepL', cat: 'ai', re: 'DEEPL|ディープエル' },
  { id: 'grammarly', name: 'Grammarly', cat: 'ai', re: 'GRAMMARLY|グラマリー', usd: true },
  { id: 'elevenlabs', name: 'ElevenLabs', cat: 'ai', re: 'ELEVEN\\s*LABS', usd: true },
  { id: 'suno', name: 'Suno', cat: 'ai', re: `${w('SUNO')}|${b('SUNO\\s*AI')}`, usd: true },
  { id: 'udio', name: 'Udio', cat: 'ai', re: w('UDIO'), usd: true },
  { id: 'runway', name: 'Runway', cat: 'ai', re: 'RUNWAY\\s*ML|RUNWAY\\s*AI', usd: true },
  { id: 'kling', name: 'Kling AI', cat: 'ai', re: `KLING|${w('KUAISHOU')}`, usd: true },
  { id: 'pika', name: 'Pika', cat: 'ai', re: 'PIKA\\s*(ART|LABS)', usd: true },
  { id: 'heygen', name: 'HeyGen', cat: 'ai', re: 'HEYGEN', usd: true },
  { id: 'leonardo', name: 'Leonardo.Ai', cat: 'ai', re: 'LEONARDO\\s*\\.?\\s*AI', usd: true },
  { id: 'stability', name: 'Stability AI', cat: 'ai', re: 'STABILITY\\s*AI|DREAMSTUDIO', usd: true },
  { id: 'novelai', name: 'NovelAI', cat: 'ai', re: 'NOVEL\\s*AI|ノベル\\s*AI', usd: true },
  { id: 'characterai', name: 'Character.AI', cat: 'ai', re: 'CHARACTER\\s*\\.?\\s*AI', usd: true },
  { id: 'gamma', name: 'Gamma', cat: 'ai', re: `${w('GAMMA')}|GAMMA\\s*APP`, usd: true },
  { id: 'jasper', name: 'Jasper', cat: 'ai', re: 'JASPER\\s*AI', usd: true },
  { id: 'otter', name: 'Otter.ai', cat: 'ai', re: 'OTTER\\s*\\.?\\s*AI', usd: true },
  { id: 'nottaai', name: 'Notta', cat: 'ai', re: 'NOTTA', usd: true },

  // ---------- クラウド・ツール ----------
  { id: 'icloud', name: 'iCloud+', cat: 'cloud', re: 'ICLOUD|アイクラウド', channel: 'appstore' },
  { id: 'appleone', name: 'Apple One', cat: 'cloud', re: 'APPLE\\s*ONE|アップル\\s*ワン', channel: 'appstore' },
  { id: 'appledev', name: 'Apple Developer Program', cat: 'cloud', re: 'APPLE\\s*DEVELOPER', usd: true },
  { id: 'googleone', name: 'Google One', cat: 'cloud', re: 'GOOGLE\\s*ONE|グーグル\\s*ワン|GOOGLE\\s*STORAGE' },
  { id: 'gworkspace', name: 'Google Workspace', cat: 'cloud', re: 'GOOGLE\\s*WORKSPACE|G\\s*SUITE|GSUITE' },
  { id: 'gcloud', name: 'Google Cloud', cat: 'cloud', re: `GOOGLE\\s*\\*?\\s*CLOUD|${w('GCP')}` },
  { id: 'aws', name: 'AWS', cat: 'cloud', re: `AMAZON\\s*WEB\\s*SERVICES|${w('AWS')}`, usd: true },
  { id: 'dropbox', name: 'Dropbox', cat: 'cloud', re: 'DROPBOX|ドロップボックス' },
  { id: 'box', name: 'Box', cat: 'cloud', re: b('BOX\\s*\\.?\\s*COM|BOX\\s*INC') },
  { id: 'onedrive', name: 'OneDrive', cat: 'cloud', re: 'ONEDRIVE|ワンドライブ' },
  { id: 'adobe', name: 'Adobe', cat: 'cloud', re: 'ADOBE|アドビ|PHOTOSHOP|フォトショ|LIGHTROOM|ライトルーム|ILLUSTRATOR|イラレ|PREMIERE|ACROBAT|CREATIVE\\s*CLOUD|FIREFLY' },
  { id: 'canva', name: 'Canva', cat: 'cloud', re: 'CANVA|キャンバ' },
  { id: 'figma', name: 'Figma', cat: 'cloud', re: 'FIGMA|フィグマ', usd: true },
  { id: 'notion', name: 'Notion', cat: 'cloud', re: 'NOTION|ノーション' },
  { id: 'evernote', name: 'Evernote', cat: 'cloud', re: 'EVERNOTE|エバーノート|BENDING\\s*SPOONS' },
  { id: 'todoist', name: 'Todoist', cat: 'cloud', re: 'TODOIST|DOIST' },
  { id: 'ticktick', name: 'TickTick', cat: 'cloud', re: 'TICKTICK' },
  { id: 'atlassian', name: 'Atlassian（Trello・Jira）', cat: 'cloud', re: 'ATLASSIAN|TRELLO|トレロ|JIRA|CONFLUENCE', usd: true },
  { id: 'miro', name: 'Miro', cat: 'cloud', re: `${w('MIRO')}|REALTIMEBOARD`, usd: true },
  { id: 'slack', name: 'Slack', cat: 'cloud', re: 'SLACK|スラック' },
  { id: 'zoom', name: 'Zoom', cat: 'cloud', re: `ZOOM\\s*(US|VIDEO|COMMUNICATIONS|\\.?\\s*COM)|${w('ZOOM')}|ズーム` },
  { id: 'chatwork', name: 'Chatwork', cat: 'cloud', re: 'CHATWORK|チャットワーク' },
  { id: 'onepassword', name: '1Password', cat: 'cloud', re: '1\\s*PASSWORD|AGILEBITS' },
  { id: 'bitwarden', name: 'Bitwarden', cat: 'cloud', re: 'BITWARDEN' },
  { id: 'lastpass', name: 'LastPass', cat: 'cloud', re: 'LASTPASS' },
  { id: 'nordvpn', name: 'NordVPN', cat: 'cloud', re: 'NORD\\s*VPN|NORD\\s*SECURITY|NORDPASS', usd: true },
  { id: 'expressvpn', name: 'ExpressVPN', cat: 'cloud', re: 'EXPRESS\\s*VPN', usd: true },
  { id: 'surfshark', name: 'Surfshark', cat: 'cloud', re: 'SURFSHARK', usd: true },
  { id: 'proton', name: 'Proton', cat: 'cloud', re: 'PROTON\\s*(AG|MAIL|VPN|PASS|DRIVE|UNLIMITED)|PROTONMAIL' },
  { id: 'norton', name: 'ノートン', cat: 'cloud', re: 'NORTON|ノートン|GEN\\s*DIGITAL|NORTONLIFELOCK' },
  { id: 'trendmicro', name: 'ウイルスバスター', cat: 'cloud', re: 'TREND\\s*MICRO|トレンドマイクロ|ウイルスバスター|ウィルスバスター' },
  { id: 'mcafee', name: 'マカフィー', cat: 'cloud', re: 'MCAFEE|マカフィー' },
  { id: 'eset', name: 'ESET', cat: 'cloud', re: `${b('ESET')}|イーセット` },
  { id: 'kaspersky', name: 'カスペルスキー', cat: 'cloud', re: 'KASPERSKY|カスペルスキー' },
  { id: 'avast', name: 'Avast', cat: 'cloud', re: 'AVAST|アバスト' },
  { id: 'github', name: 'GitHub', cat: 'cloud', re: 'GITHUB|ギットハブ', usd: true },
  { id: 'gitlab', name: 'GitLab', cat: 'cloud', re: 'GITLAB', usd: true },
  { id: 'vercel', name: 'Vercel', cat: 'cloud', re: 'VERCEL', usd: true },
  { id: 'netlify', name: 'Netlify', cat: 'cloud', re: 'NETLIFY', usd: true },
  { id: 'cloudflare', name: 'Cloudflare', cat: 'cloud', re: 'CLOUDFLARE', usd: true },
  { id: 'heroku', name: 'Heroku', cat: 'cloud', re: 'HEROKU', usd: true },
  { id: 'digitalocean', name: 'DigitalOcean', cat: 'cloud', re: 'DIGITAL\\s*OCEAN', usd: true },
  { id: 'render', name: 'Render', cat: 'cloud', re: 'RENDER\\s*\\.?\\s*COM', usd: true },
  { id: 'xserver', name: 'エックスサーバー', cat: 'cloud', re: 'XSERVER|エックスサーバー' },
  { id: 'sakura', name: 'さくらインターネット', cat: 'cloud', re: 'さくらインターネット|SAKURA\\s*INTERNET' },
  { id: 'conoha', name: 'ConoHa', cat: 'cloud', re: 'CONOHA|コノハ' },
  { id: 'onamae', name: 'お名前.com', cat: 'cloud', re: 'お名前\\s*\\.?\\s*COM|ONAMAE' },
  { id: 'lolipop', name: 'ロリポップ！', cat: 'cloud', re: 'ロリポップ|LOLIPOP|ムームードメイン|MUUMUU|GMO\\s*PEPABO' },
  { id: 'wix', name: 'Wix', cat: 'cloud', re: `${w('WIX')}|WIX\\s*\\.?\\s*COM` },
  { id: 'wordpress', name: 'WordPress.com', cat: 'cloud', re: 'WORDPRESS|AUTOMATTIC' },
  { id: 'squarespace', name: 'Squarespace', cat: 'cloud', re: 'SQUARESPACE', usd: true },
  { id: 'shopify', name: 'Shopify', cat: 'cloud', re: 'SHOPIFY|ショッピファイ' },
  { id: 'jetbrains', name: 'JetBrains', cat: 'cloud', re: 'JETBRAINS' },
  { id: 'setapp', name: 'Setapp', cat: 'cloud', re: 'SETAPP|MACPAW|CLEANMYMAC', usd: true },
  { id: 'parallels', name: 'Parallels', cat: 'cloud', re: 'PARALLELS' },
  { id: 'autodesk', name: 'Autodesk', cat: 'cloud', re: 'AUTODESK|オートデスク' },
  { id: 'unity', name: 'Unity', cat: 'cloud', re: 'UNITY\\s*(TECHNOLOGIES|PRO|PLUS)|UNITY3D', usd: true },
  { id: 'clipstudio', name: 'CLIP STUDIO PAINT', cat: 'cloud', re: 'CLIP\\s*STUDIO|クリスタ|CELSYS|セルシス' },
  { id: 'filmora', name: 'Filmora', cat: 'cloud', re: 'FILMORA|WONDERSHARE' },
  { id: 'capcut', name: 'CapCut', cat: 'cloud', re: 'CAPCUT|キャップカット' },
  { id: 'picsart', name: 'Picsart', cat: 'cloud', re: 'PICSART' },
  { id: 'freee', name: 'freee', cat: 'cloud', re: `${w('FREEE')}|${b('FREEE\\s*(INC|株式会社|会計|人事)')}|フリー株式会社` },
  { id: 'moneyforward', name: 'マネーフォワード', cat: 'cloud', re: 'マネーフォワード|MONEY\\s*FORWARD|マネフォ' },
  { id: 'zaim', name: 'Zaim', cat: 'cloud', re: `${w('ZAIM')}|ザイム` },
  { id: 'yayoi', name: '弥生', cat: 'cloud', re: '弥生|YAYOI' },
  { id: 'moneytree', name: 'Moneytree', cat: 'cloud', re: 'MONEYTREE|マネーツリー' },

  // ---------- ゲーム ----------
  { id: 'nso', name: 'Nintendo Switch Online', cat: 'game', re: 'NINTENDO|ニンテンドー|任天堂|SWITCH\\s*ONLINE' },
  { id: 'psplus', name: 'PlayStation Plus', cat: 'game', re: `PLAYSTATION|プレイステーション|プレステ|${b('PS\\s*PLUS')}` },
  { id: 'gamepass', name: 'Xbox Game Pass', cat: 'game', re: 'GAME\\s*PASS|XBOX|ゲームパス' },
  { id: 'minecraft', name: 'Minecraft Realms', cat: 'game', re: 'MINECRAFT|マインクラフト|マイクラ|MOJANG' },
  { id: 'applearcade', name: 'Apple Arcade', cat: 'game', re: 'APPLE\\s*ARCADE|アップル\\s*アーケード', channel: 'appstore' },
  { id: 'playpass', name: 'Google Play Pass', cat: 'game', re: 'PLAY\\s*PASS|プレイパス', channel: 'googleplay' },
  { id: 'eaplay', name: 'EA Play', cat: 'game', re: `${b('EA\\s*PLAY')}|ELECTRONIC\\s*ARTS` },
  { id: 'ubisoft', name: 'Ubisoft+', cat: 'game', re: 'UBISOFT|ユービーアイ' },
  { id: 'squareenix', name: 'スクウェア・エニックス（DQX・FF14 など）', cat: 'game', re: `${w('FF\\s*14')}|SQUARE\\s*ENIX|スクウェア|スクエニ|ドラクエ|ドラゴンクエスト|FINAL\\s*FANTASY|FFXIV` },
  { id: 'geforcenow', name: 'GeForce NOW', cat: 'game', re: 'GEFORCE\\s*NOW|NVIDIA' },
  { id: 'epic', name: 'Fortnite クルー', cat: 'game', re: 'EPIC\\s*GAMES|FORTNITE|フォートナイト' },
  { id: 'roblox', name: 'Roblox Premium', cat: 'game', re: 'ROBLOX|ロブロックス' },
  { id: 'pokemonhome', name: 'Pokémon HOME', cat: 'game', re: 'POKEMON\\s*HOME|ポケモン\\s*HOME|ポケモン\\s*ホーム' },
  { id: 'niantic', name: 'ポケモンGO など（Niantic）', cat: 'game', re: 'NIANTIC|ナイアンティック|ポケモン\\s*GO|ポケGO' },
  { id: 'hoyoverse', name: 'HoYoverse（原神・スターレイル など）', cat: 'game', re: 'HOYOVERSE|COGNOSPHERE|MIHOYO|原神|スターレイル|ゼンレス' },
  { id: 'discord', name: 'Discord Nitro', cat: 'game', re: 'DISCORD|ディスコード|ディスコ\\s*NITRO', usd: true },

  // ---------- 本・マンガ・雑誌・ニュース ----------
  { id: 'kindleu', name: 'Kindle Unlimited', cat: 'other', re: 'KINDLE|キンドル' },
  { id: 'dmagazine', name: 'dマガジン', cat: 'other', re: 'D\\s*マガジン|DMAGAZINE' },
  { id: 'rakutenmag', name: '楽天マガジン', cat: 'other', re: '楽天\\s*マガジン' },
  { id: 'bookhoudai', name: 'ブック放題', cat: 'other', re: 'ブック放題' },
  { id: 'cmoa', name: 'コミックシーモア', cat: 'other', re: 'シーモア|CMOA|NTT\\s*SOLMARE' },
  { id: 'jumpplus', name: '少年ジャンプ＋', cat: 'other', re: '少年ジャンプ|ジャンプ\\s*(\\+|＋|プラス)|SHONEN\\s*JUMP' },
  { id: 'magapoke', name: 'マガポケ', cat: 'other', re: 'マガポケ|マガジン\\s*ポケット' },
  { id: 'linemanga', name: 'LINEマンガ', cat: 'other', re: 'LINE\\s*マンガ|LINE\\s*MANGA' },
  { id: 'piccoma', name: 'ピッコマ', cat: 'other', re: 'ピッコマ|PICCOMA|KAKAO' },
  { id: 'mechacomic', name: 'めちゃコミック', cat: 'other', re: 'めちゃ\\s*コミ|AMUTUS' },
  { id: 'mangaoukoku', name: 'まんが王国', cat: 'other', re: 'まんが王国|マンガ王国' },
  { id: 'ebookjapan', name: 'ebookjapan', cat: 'other', re: 'EBOOK\\s*JAPAN|イーブック' },
  { id: 'booklive', name: 'BookLive!', cat: 'other', re: 'BOOK\\s*LIVE|ブックライブ' },
  { id: 'honto', name: 'honto', cat: 'other', re: `${w('HONTO')}|${b('HONTO\\s*\\.?\\s*JP')}` },
  { id: 'kobo', name: '楽天Kobo', cat: 'other', re: `楽天\\s*KOBO|RAKUTEN\\s*KOBO|${w('KOBO')}` },
  { id: 'dlsite', name: 'DLsite', cat: 'other', re: 'DLSITE|DL\\s*サイト' },
  { id: 'nikkei', name: '日経電子版', cat: 'other', re: '日経|NIKKEI' },
  { id: 'newspicks', name: 'NewsPicks', cat: 'other', re: 'NEWSPICKS|ニューズピックス' },
  { id: 'asahi', name: '朝日新聞デジタル', cat: 'other', re: '朝日新聞|ASAHI\\s*SHIMBUN|ASAHI\\s*\\.?\\s*COM|朝日デジタル' },
  { id: 'yomiuri', name: '読売新聞', cat: 'other', re: '読売|YOMIURI' },
  { id: 'mainichi', name: '毎日新聞', cat: 'other', re: '毎日新聞|MAINICHI' },
  { id: 'sankei', name: '産経新聞', cat: 'other', re: '産経|SANKEI' },
  { id: 'toyokeizai', name: '東洋経済オンライン', cat: 'other', re: '東洋経済|TOYO\\s*KEIZAI' },
  { id: 'diamond', name: 'ダイヤモンド・オンライン', cat: 'other', re: 'ダイヤモンド\\s*(オンライン|プレミアム|ONLINE)|DIAMOND\\s*ONLINE' },
  { id: 'bunshun', name: '文春電子版', cat: 'other', re: '文春' },
  { id: 'wsj', name: 'ウォール・ストリート・ジャーナル', cat: 'other', re: `${w('WSJ')}|WALL\\s*STREET\\s*JOURNAL|DOW\\s*JONES` },
  { id: 'nyt', name: 'New York Times', cat: 'other', re: `NYTIMES|NEW\\s*YORK\\s*TIMES|${w('NYT')}`, usd: true },
  { id: 'economist', name: 'The Economist', cat: 'other', re: 'ECONOMIST|エコノミスト' },
  { id: 'bloomberg', name: 'Bloomberg', cat: 'other', re: 'BLOOMBERG|ブルームバーグ' },
  { id: 'medium', name: 'Medium', cat: 'other', re: 'MEDIUM\\s*\\.?\\s*COM|MEDIUM\\s*CORP|A\\s*MEDIUM\\s*CORPORATION', usd: true },
  { id: 'note', name: 'note（メンバーシップ・マガジン）', cat: 'other', re: `${b('NOTE\\s*(INC|株式会社|メンバーシップ|マガジン)|NOTE\\s*\\.?\\s*COM')}|ノート\\s*メンバーシップ` },
  { id: 'substack', name: 'Substack', cat: 'other', re: 'SUBSTACK', usd: true },

  // ---------- 学び ----------
  { id: 'duolingo', name: 'Duolingo', cat: 'other', re: 'DUOLINGO|デュオリンゴ' },
  { id: 'studysapuri', name: 'スタディサプリ', cat: 'other', re: 'スタディサプリ|STUDY\\s*SAPURI|スタサプ' },
  { id: 'zkai', name: 'Z会', cat: 'other', re: 'Z\\s*会|ZKAI' },
  { id: 'benesse', name: '進研ゼミ・こどもちゃれんじ', cat: 'other', re: 'ベネッセ|BENESSE|進研ゼミ|こどもちゃれんじ' },
  { id: 'schoo', name: 'Schoo', cat: 'other', re: w('SCHOO') },
  { id: 'coursera', name: 'Coursera', cat: 'other', re: 'COURSERA|コーセラ', usd: true },
  { id: 'udemy', name: 'Udemy', cat: 'other', re: 'UDEMY|ユーデミー' },
  { id: 'progate', name: 'Progate', cat: 'other', re: 'PROGATE|プロゲート' },
  { id: 'dotinstall', name: 'ドットインストール', cat: 'other', re: 'ドットインストール|DOTINSTALL' },
  { id: 'dmmeikaiwa', name: 'DMM英会話', cat: 'other', re: 'DMM\\s*英会話|DMM\\s*EIKAIWA' },
  { id: 'rarejob', name: 'レアジョブ英会話', cat: 'other', re: 'レアジョブ|RAREJOB' },
  { id: 'nativecamp', name: 'ネイティブキャンプ', cat: 'other', re: 'ネイティブ\\s*キャンプ|NATIVE\\s*CAMP' },
  { id: 'cambly', name: 'Cambly', cat: 'other', re: 'CAMBLY|キャンブリー' },
  { id: 'speak', name: 'スピーク（Speak）', cat: 'other', re: 'スピーク|SPEAK\\s*(APP|EASY\\s*LABS)' },
  { id: 'elsa', name: 'ELSA Speak', cat: 'other', re: `ELSA\\s*SPEAK|${w('ELSA')}` },
  { id: 'brilliant', name: 'Brilliant', cat: 'other', re: 'BRILLIANT\\s*\\.?\\s*ORG', usd: true },
  { id: 'masterclass', name: 'MasterClass', cat: 'other', re: 'MASTERCLASS|マスタークラス', usd: true },

  // ---------- 運動・健康 ----------
  { id: 'chocozap', name: 'chocoZAP', cat: 'other', re: 'CHOCO\\s*ZAP|チョコザップ|RIZAP|ライザップ' },
  { id: 'anytime', name: 'エニタイムフィットネス', cat: 'other', re: 'エニタイム|ANYTIME\\s*FITNESS' },
  { id: 'goldsgym', name: 'ゴールドジム', cat: 'other', re: 'ゴールドジム|GOLD\\s*\'?S\\s*GYM' },
  { id: 'curves', name: 'カーブス', cat: 'other', re: 'カーブス|CURVES' },
  { id: 'tipness', name: 'ティップネス', cat: 'other', re: 'ティップネス|TIPNESS' },
  { id: 'konami', name: 'コナミスポーツクラブ', cat: 'other', re: 'コナミ\\s*スポーツ|KONAMI\\s*SPORTS' },
  { id: 'joyfit', name: 'JOYFIT', cat: 'other', re: 'JOYFIT|ジョイフィット' },
  { id: 'central', name: 'セントラルスポーツ', cat: 'other', re: 'セントラル\\s*スポーツ|CENTRAL\\s*SPORTS' },
  { id: 'renaissance', name: 'スポーツクラブ ルネサンス', cat: 'other', re: 'スポーツクラブ\\s*ルネサンス|RENAISSANCE\\s*INC' },
  { id: 'lava', name: 'LAVA（ホットヨガ）', cat: 'other', re: `${w('LAVA')}|ホットヨガ` },
  { id: 'soelu', name: 'SOELU', cat: 'other', re: 'SOELU|ソエル' },
  { id: 'leanbody', name: 'LEAN BODY', cat: 'other', re: 'LEAN\\s*BODY|リーンボディ' },
  { id: 'fitbit', name: 'Fitbit Premium', cat: 'other', re: 'FITBIT|フィットビット' },
  { id: 'applefitness', name: 'Apple Fitness+', cat: 'other', re: 'APPLE\\s*FITNESS', channel: 'appstore' },
  { id: 'strava', name: 'Strava', cat: 'other', re: 'STRAVA|ストラバ' },
  { id: 'asken', name: 'あすけん', cat: 'other', re: 'あすけん|ASKEN' },
  { id: 'calm', name: 'Calm', cat: 'other', re: `${b('CALM')}(?:\\s*\\.?\\s*COM|\\s*APP)?(?![A-Z0-9])`, usd: true },
  { id: 'headspace', name: 'Headspace', cat: 'other', re: 'HEADSPACE|ヘッドスペース', usd: true },

  // ---------- 食べ物・買い物・暮らし ----------
  { id: 'uberone', name: 'Uber One', cat: 'other', re: 'UBER\\s*ONE|ウーバー\\s*ワン' },
  { id: 'woltplus', name: 'Wolt+', cat: 'other', re: 'WOLT\\s*(\\+|PLUS)|ウォルト\\s*プラス' },
  { id: 'demaecan', name: '出前館', cat: 'other', re: '出前館|DEMAE\\s*CAN' },
  { id: 'menu', name: 'menu', cat: 'other', re: 'MENU\\s*PASS|メニュー\\s*パス|MENU\\s*株式会社' },
  { id: 'costco', name: 'コストコ年会費', cat: 'other', re: 'COSTCO|コストコ' },
  { id: 'nosh', name: 'nosh（ナッシュ）', cat: 'other', re: `${w('NOSH')}|ナッシュ` },
  { id: 'basefood', name: 'BASE FOOD', cat: 'other', re: 'BASE\\s*FOOD|ベースフード' },
  { id: 'oisix', name: 'Oisix', cat: 'other', re: 'OISIX|オイシックス' },
  { id: 'palsystem', name: 'パルシステム', cat: 'other', re: 'パルシステム|PALSYSTEM' },
  { id: 'coop', name: 'コープの宅配', cat: 'other', re: 'コープデリ|おうちコープ|生活協同組合|生協' },
  { id: 'yoshikei', name: 'ヨシケイ', cat: 'other', re: 'ヨシケイ|YOSHIKEI' },
  { id: 'greenspoon', name: 'GREEN SPOON', cat: 'other', re: 'GREEN\\s*SPOON|グリーンスプーン' },
  { id: 'timescar', name: 'タイムズカー', cat: 'other', re: 'タイムズ\\s*カー|TIMES\\s*CAR' },
  { id: 'careco', name: 'カレコ', cat: 'other', re: 'カレコ|CARECO' },
  { id: 'luup', name: 'LUUP', cat: 'other', re: 'LUUP|ループ\\s*(パス|PASS)' },
  { id: 'nhk', name: 'NHK受信料', cat: 'video', re: 'NHK|日本放送協会|受信料' },

  // ---------- SNS・交流・応援 ----------
  { id: 'xpremium', name: 'X Premium', cat: 'other', re: `${b('X\\s*(CORP|PREMIUM)')}|TWITTER|ツイッター\\s*(ブルー|プレミアム)|${w('X')}\\s*プレミアム`, usd: true },
  { id: 'metaverified', name: 'Meta認証', cat: 'other', re: 'META\\s*VERIFIED|メタ認証' },
  { id: 'snapchat', name: 'Snapchat+', cat: 'other', re: 'SNAPCHAT', usd: true },
  { id: 'telegram', name: 'Telegram Premium', cat: 'other', re: 'TELEGRAM\\s*PREMIUM' },
  { id: 'linestamp', name: 'LINEスタンプ プレミアム', cat: 'other', re: 'LINE\\s*スタンプ\\s*プレミアム|LINE\\s*STAMP\\s*PREMIUM' },
  { id: 'pixivfanbox', name: 'pixivFANBOX', cat: 'other', re: 'FANBOX|ファンボックス|PIXIV|ピクシブ' },
  { id: 'fantia', name: 'Fantia', cat: 'other', re: 'FANTIA|ファンティア' },
  { id: 'cien', name: 'Ci-en', cat: 'other', re: `CI\\s*-\\s*EN|${w('CIEN')}` },
  { id: 'patreon', name: 'Patreon', cat: 'other', re: 'PATREON|パトレオン', usd: true },
  { id: 'buymeacoffee', name: 'Buy Me a Coffee', cat: 'other', re: 'BUY\\s*ME\\s*A\\s*COFFEE', usd: true },
  { id: 'pairs', name: 'Pairs', cat: 'other', re: `${w('PAIRS')}|ペアーズ|エウレカ` },
  { id: 'omiai', name: 'Omiai', cat: 'other', re: 'OMIAI' },
  { id: 'tapple', name: 'タップル', cat: 'other', re: 'タップル|TAPPLE' },
  { id: 'tinder', name: 'Tinder', cat: 'other', re: 'TINDER|ティンダー' },
  { id: 'bumble', name: 'Bumble', cat: 'other', re: 'BUMBLE' },
  { id: 'marrish', name: 'マリッシュ', cat: 'other', re: 'マリッシュ|MARRISH' },
  { id: 'zexy', name: 'ゼクシィ縁結び', cat: 'other', re: 'ゼクシィ|ZEXY' },

  // ---------- 携帯会社のオプション・ポイント会員 ----------
  { id: 'pontapass', name: 'Pontaパス（旧スマートパス）', cat: 'other', re: 'PONTA\\s*パス|PONTA\\s*PASS|スマート\\s*パス|SMART\\s*PASS' },
  { id: 'lyp', name: 'LYPプレミアム', cat: 'other', re: `${b('LYP')}|YAHOO\\s*!?\\s*プレミアム|ヤフー\\s*プレミアム|LINE\\s*ヤフー` },
  { id: 'rakutenunlimit', name: '楽天モバイルのオプション', cat: 'other', re: '楽天モバイル\\s*(オプション|プレミアム)' },

  // ---------- 親会社の名前だけで当たるもの（具体的なものより下に置く） ----------
  { id: 'm365', name: 'Microsoft 365', cat: 'cloud', re: 'MICROSOFT|MSFT|OFFICE\\s*365|マイクロソフト' },
  { id: 'dmm', name: 'DMMプレミアム（DMM TV）', cat: 'video', re: `${b('DMM')}|ディーエムエム` },
  { id: 'amazonprime', name: 'Amazonプライム', cat: 'other', re: 'AMAZON\\s*PRIME|AMZN\\s*PRIME|PRIME\\s*VIDEO|アマゾン\\s*プライム|プライム\\s*(会費|ビデオ)' },
  { id: 'appstore', name: 'App Store の課金', cat: 'other', re: 'APPLE\\s*\\.?\\s*COM\\s*/?\\s*BILL|ITUNES', generic: true, channel: 'appstore' },
  { id: 'googleplay', name: 'Google Play の課金', cat: 'other', re: 'GOOGLE\\s*\\*?\\s*PLAY', generic: true, channel: 'googleplay' },
  { id: 'amazonprime', name: 'Amazonプライム', cat: 'other', re: 'AMAZON|アマゾン', textOnly: true, hint: 'Amazon の買い物ではなく、プライム会員の料金として仮登録しています' }
];

export const SERVICES = LIST.map((s) => ({ ...s, rx: new RegExp(s.re, 'iu') }));
export const SERVICE_COUNT = new Set(LIST.filter((s) => !s.generic && !s.textOnly).map((s) => s.id)).size;

export const serviceById = (id) => SERVICES.find((s) => s.id === id && !s.textOnly) || null;

// 明細の利用先（またはサービス名）から辞書のサービスを探す
export function matchMerchant(merchant) {
  const k = compact(merchant);
  if (!k) return null;
  return SERVICES.find((s) => !s.textOnly && s.rx.test(k)) || null;
}
